apiVersion: v1
kind: Pod
metadata:
  name: demo-readinessprob
  namespace: demo
  labels:
    app: demo
spec:
  containers:
    - name: demo
      image: gcr.io/minikube-385711/demo:v2.0.0
      readinessProbe:
        httpGet:
          path: /alive
          port: 8080
        initialDelaySeconds: 5
        periodSeconds: 5
