apiVersion: batch/v1
kind: CronJob
metadata:
  name: demo-cronjob
  namespace: demo
spec:
  schedule: "0 1 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: demo-cronjob
              image: busybox
              command: ["sh", "-c", "rm -rf /tmp/*"]
          restartPolicy: OnFailure
