apiVersion: v1
kind: Pod
metadata:
  name: demo-livenessprob
  namespace: demo
  labels:
    app: demo
spec:
  containers:
    - name: demo
      image: gcr.io/minikube-385711/demo:v1.0.0
      ports:
        - containerPort: 8080
      livenessProbe:
        httpGet:
          path: /
          port: 8080
        initialDelaySeconds: 5
        periodSeconds: 10
