apiVersion: v1
kind: Pod
metadata:
  name: demo-resources
spec:
  containers:
    - name: kuard
      image: gcr.io/kuar-demo/kuard-arm64:1
      resources:
        requests:
          cpu: 100m
          memory: 125Mi
        limits:
          cpu: 100m
          memory: 256Mi
