---
apiVersion: v1
kind: Pod
metadata:
  name: demo-app
  labels:
    app: demo
spec:
  containers:
    - name: demo
      image: gcr.io/minikube-385711/demo:v1.0.0
      ports:
        - containerPort: 8080
